// Code generated by "stringer -type=Status"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocalStorageAvailabilityLow-0]
	_ = x[LocalStorageAvailabilityExhausted-1]
	_ = x[BatteryLow-2]
	_ = x[BatteryCharging-3]
	_ = x[BatteryFullyCharged-4]
	_ = x[ConnectionEstablished-5]
	_ = x[ConnectionNotEstablished-6]
}

const _Status_name = "LocalStorageAvailabilityLowLocalStorageAvailabilityExhaustedBatteryLowBatteryChargingBatteryFullyChargedConnectionEstablishedConnectionNotEstablished"

var _Status_index = [...]uint8{0, 27, 60, 70, 85, 104, 125, 149}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
